### ISSUE TITLE
warning for skipped hrefs leading to unhanded exception

### ISSUE THREAD

**Issue by jludwig** [untitaker/vdirsyncer#113] opened 2014-09-08 23:19 UTC
Hello,

First of all, great work with this project. I am very close to throwing away Outlook completely. This is the last step!

Now for the issue:

I am using Davmail as the middleman between Outlook Exchange 2011 and vdirsyncer, and for the most part it works flawlessly. However, when I try syncing the 'all staff' calendar, the biggest one, I get a page full of warnings that look like this:

`warning: Skipping identical href: /public/example.com/All%20Staff%20Calendar/Foobar%20-%20Appt.EML`

After about five minutes, it reaches the end and gives back an unhanded exception that says:

```
Unhandled exception occured while syncing all_staff_calendar.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/vdirsyncer/cli.py", line 393, in sync_collection
    force_delete=status_name in force_delete
  File "/usr/local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 129, in sync
    list_b = prepare_list(storage_b, b_href_to_status)
  File "/usr/local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 76, in prepare_list
    prefetch(storage, rv, download)
  File "/usr/local/lib/python2.7/site-packages/vdirsyncer/sync.py", line 86, in prefetch
    for href, item, etag in storage.get_multi(hrefs):
  File "/usr/local/lib/python2.7/site-packages/vdirsyncer/storage/dav.py", line 333, in get_multi
    .format(href, hrefs_left))
KeyError: "/public/example.com/Shared%20All%20Staff/Foobar%20Leave%20early.EML doesn't exist in set([massive freaking array])
```

When I add debug messaging, it looks pretty standard. These are the last lines displayed before the error:

```
debug: X-MICROSOFT-CDO-APPT-SEQUENCE:0
debug: X-MICROSOFT-CDO-OWNERAPPTID:2112067640
debug: X-MICROSOFT-CDO-BUSYSTATUS:FREE
debug: X-MICROSOFT-CDO-INTENDEDSTATUS:BUSY
debug: X-MICROSOFT-CDO-ALLDAYEVENT:TRUE
debug: X-MICROSOFT-CDO-IMPORTANCE:1
debug: X-MICROSOFT-CDO-INSTTYPE:0
debug: X-MICROSOFT-DISALLOW-COUNTER:FALSE
debug: END:VEVENT
debug: END:VCALENDAR
debug: </C:calendar-data><D:getetag>2014-05-05T20:29:17Z</D:getetag></D:prop><D:status>HTTP/1.1 200 OK</D:status></D:propstat></D:response></D:multistatus>
```

Please let me know any additional information that would help. Thank you.

**Comment by untitaker** [comment] 2015-01-01 18:03
Closing this as a duplicate of #144.

**Closed by untitaker** 2015-01-01 18:03 UTC
Labels: 3rd party, bug, DAV, server compat
