### ISSUE TITLE
[repair]: Unhandled exception

### ISSUE THREAD

**Issue by matthiasbeyer** [untitaker/vdirsyncer#281] opened 2015-10-13 13:47 UTC
Hi, here's what happened:

```
$ vdirsyncer sync
error: m_calendar/contact_birthdays: Storage "m_calendar_remote/contact_birthdays" contains multiple items with the same UID or even content. Vdirsyncer will now abort the synchronization of this collection, because the fix for this is not clear; It could be the result of a badly behaving server. You can try running:
error: 
error:     vdirsyncer repair m_calendar_remote/contact_birthdays
error: 
error: But make sure to have a backup of your data in some form. The offending hrefs are:
error: 
error: '/oc/remote.php/caldav/calendars/m/contact_birthdays/local::3::88.ics'
error: '/oc/remote.php/caldav/calendars/m/contact_birthdays/local::3::11.ics'
Copying (uploading) item 15fbe420-0c5f-4941-83a2-de00e06429fc-caldavsyncadapter to m_calendar_local/personal
Copying (uploading) item 9c63366c-9f95-4c5d-81d3-24abbb87087b-caldavsyncadapter to m_calendar_local/personal
```

I than tried as suggested:

```
$ vdirsyncer repair m_calendar_remote/contact_birthdays
warning: This operation will take a very long time.
warning: It's recommended to turn off other client's synchronization features.
Do you want to continue? [y/N]: y
Discovering collections (skipping cache).
Repairing m_calendar_remote/contact_birthdays
warning: Make sure no other program is talking to the server.
[0/2] Processing /oc/remote.php/caldav/calendars/m/contact_birthdays/local::3::11.ics
warning: No UID, assigning random one.
Unhandled exception occured.
Traceback (most recent call last):
  File "/nix/store/18gfd9fbjxbdh0iz2amkdnjix3r7rc31-vdirsyncer-0.6.0/lib/python2.7/site-packages/vdirsyncer/cli/__init__.py", line 35, in inner
    f(*a, **kw)
  File "/nix/store/18gfd9fbjxbdh0iz2amkdnjix3r7rc31-vdirsyncer-0.6.0/lib/python2.7/site-packages/vdirsyncer/cli/__init__.py", line 220, in repair
    repair_collection(general, all_pairs, all_storages, collection)
  File "/nix/store/18gfd9fbjxbdh0iz2amkdnjix3r7rc31-vdirsyncer-0.6.0/lib/python2.7/site-packages/vdirsyncer/cli/tasks.py", line 109, in repair_collection
    repair_storage(storage)
  File "/nix/store/18gfd9fbjxbdh0iz2amkdnjix3r7rc31-vdirsyncer-0.6.0/lib/python2.7/site-packages/vdirsyncer/repair.py", line 38, in repair_storage
    assert new_item.uid
AssertionError
```

**Comment by matthiasbeyer** [comment] 2015-10-13 13:51
Just `curl`d the reported URLS:

```
error: '/oc/remote.php/caldav/calendars/m/contact_birthdays/local::3::88.ics'
error: '/oc/remote.php/caldav/calendars/m/contact_birthdays/local::3::11.ics'
```

both contain:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//ownCloud//NONSGML Contacts 0.4.0.0//EN
CALSCALE:GREGORIAN
END:VCALENDAR
```

**Comment by benjaminfrank** [comment] 2015-10-13 14:50
You might want to check #262. It looks like Owncloud is broken in one way or the other regarding contact birthdays.

**Comment by matthiasbeyer** [comment] 2015-10-13 14:59
Do you know whether the patch referred to in #261 is already in owncloud/calendar? I'm running latest owncloud.

**Comment by benjaminfrank** [comment] 2015-10-13 15:05
Sorry no idea. After it became clean ownlcoud 8.1 is rather broken (#255), I refrained from updating and added the patch myself.

**Comment by untitaker** [comment] 2015-10-13 17:14
There's no release that contains that fix (If you click on a commit, you'll see the branches and tags whose history the commit is part of)

* In the short term: Patch your ownCloud manually
* In the mid term: Wait for release
* In the long term: Just stop using ownCloud, it's getting buggier with every release. The patch that fixes this issue doesn't even contain tests, so I'm sure everything will regress in about three months. I wouldn't know of an alternative that has a birthday calendar, but Baikal is very good otherwise.

I'm going to close this as a duplicate of #261.

**Closed by untitaker** 2015-10-13 17:14 UTC
