### ISSUE TITLE
ownCloud returns some weird ics files which vdirsyncer doesn't know how to handle

### ISSUE THREAD

**Issue by sixtyfive** [untitaker/vdirsyncer#261] opened 2015-09-02 12:50 UTC
When I sync, this happens:

```
error: calendar/contact_birthdays: Storage "calendar_remote/contact_birthdays" contains multiple items with the same UID or even content. Vdirsyncer will now abort the synchronization of this collection, because the fix for this is not clear; It could be the result of a badly behaving server. You can try running:
error: 
error:     vdirsyncer repair calendar_remote/contact_birthdays
error: 
error: But make sure to have a backup of your data in some form. The offending hrefs are:
error: 
error: '/remote.php/caldav/calendars/me@mydomain/contact_birthdays/local::36::3166.ics'
error: '/remote.php/caldav/calendars/me@mydomain/contact_birthdays/local::6::2658.ics'
```

If I download either of these with wget, they turn out both look like this:

```
BEGIN:VCALENDAR
VERSION:2.0
PRODID:-//ownCloud//NONSGML Contacts 0.4.0.0//EN
CALSCALE:GREGORIAN
END:VCALENDAR
```

Perhaps it's some sort of special ownCloud thing and vdirsyncer just needs to know that it can be ignored?

**Comment by untitaker** [comment] 2015-09-02 12:54
If this is really everything that is in each of those files, I think this is a ownCloud bug.

**Comment by sixtyfive** [comment] 2015-09-02 18:33
I swear by a holy book of your choice that that is all wget is receiving when requesting those files. Trying to investigate it from ownCloud's side...

**Comment by untitaker** [comment] 2015-09-02 18:44
ownCloud's error log is usually very informative. It might be that this empty event is caused by a corrupted or somehow unreadable contact.

**Comment by sixtyfive** [comment] 2015-09-02 20:01
Okay, so after not finding anything useful in the logs (might just be because there's so much to read and understand) I found this more or less by coincidence: https://github.com/owncloud/contacts/pull/970/files ... hotfixed it and, voila, problem be gone! :)

**Comment by untitaker** [comment] 2015-09-02 20:08
I see, the fix totally makes sense. I'm closing this though because vdirsyncer can't really do anything about it.

**Closed by untitaker** 2015-09-02 20:08 UTC
Labels: 3rd party, bug
