### ISSUE TITLE
vdirsyncer breaks on syncing weird Outlook fields in vcf files

### ISSUE THREAD

**Issue by dvzrv** [untitaker/vdirsyncer#277] opened 2015-10-01 09:59 UTC
Hey there, this is me running Arch Linux, Python 3.4.3, vdirsyncer 0.6.0.

I (unfortunately) have some Outlook clients in my network, synchronizing with the OwnCloud we use. Those have the nice behavior of manipulating each vcard they sync with and adding their weird M$ fields (that most likely only Outlook understands).
Most clients sync just fine with this (probably ignoring the fields when reading the vcard).
Vdirsyncer however breaks/ doesn't sync properly when there are vcards with the following fields:

    X-MS-OL-DESIGN:<card xmlns="http://schemas.microsoft.com/office/outlook/12/
    electronicbusinesscards" ver="1.0" layout="left" bgcolor="ffffff"><img xml
    ns="" align="tleft" area="32" use="photo"/><fld xmlns="" prop="name" align
    ="left" dir="ltr" style="b" color="000000" size="10"/><fld xmlns="" prop="
    org" align="left" dir="ltr" color="000000" size="8"/><fld xmlns="" prop="b
    lank" size="8"/><fld xmlns="" prop="telwork" align="left" dir="ltr" color=
    "000000" size="8"><label align="right" color="626262">Geschäftlich</label
    ></fld><fld xmlns="" prop="email" align="left" dir="ltr" color="000000" si
    ze="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" si
    ze="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" si
    ze="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" si
    ze="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" si
    ze="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank" si
    ze="8"/><fld xmlns="" prop="blank" size="8"/></card>
    X-MS-OL-DEFAULT-POSTAL-ADDRESS:0

Is there a way for vdirsyncer to also ignore those fields? I know they are useless bloaty M$ XML blah, but it breaks functionality :/

This is the normal output. If you need debug output, let me know!

    warning: Skipping '/.cloudy/remote.php/carddav/addressbooks/7e446f3d-c45d-4dd0-bd89-4f28356a3f1a/team/', etag property is missing.
    warning: Server sent unsolicited item: /.cloudy/remote.php/carddav/addressbooks/7e446f3d-c45d-4dd0-bd89-4f28356a3f1a/team/
    Unhandled exception occured for akt_contacts/team.
    Traceback (most recent call last):
     File "/usr/lib/python3.4/site-packages/vdirsyncer/cli/tasks.py", line 65, in sync_collection
      force_delete=force_delete
    File "/usr/lib/python3.4/site-packages/vdirsyncer/sync.py", line 163, in sync
      b_info.prepare_idents(storage_a.read_only)
    File "/usr/lib/python3.4/site-packages/vdirsyncer/sync.py", line 111, in prepare_idents
      if prefetch else ()):
    File "/usr/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line 452, in get_multi
      raise exceptions.NotFoundError(href)
    vdirsyncer.exceptions.NotFoundError: /.cloudy/remote.php/carddav/addressbooks/7e446f3d-c45d-4dd0-bd89-4f28356a3f1a/team/ebf32dc0-d6e1-4abc-abb2-14cb9f92f2c7@www.myserver.com.vcf

**Comment by untitaker** [comment] 2015-10-01 13:33
Try running `vdirsyncer repair` on all calendars on both sides, maybe it helps.

I suspect a serverside bug and can't see how properties have anything to do with this, if the above command doesn't help I'd need the debug log (per email found on my profile).

On 1 October 2015 11:59:50 CEST, David Runge <notifications@github.com> wrote:
>Hey there, this is me running Arch Linux, Python 3.4.3, vdirsyncer
>0.6.0.
>
>I (unfortunately) have some Outlook clients in my network,
>synchronizing with the OwnCloud we use. Those have the nice behavior of
>manipulating each vcard they sync with and adding their weird M$ fields
>(that most likely only Outlook understands).
>Most clients sync just fine with this (probably ignoring the fields
>when reading the vcard).
>Vdirsyncer however breaks/ doesn't sync properly when there are vcards
>with the following fields:
>
>X-MS-OL-DESIGN:<card
>xmlns="http://schemas.microsoft.com/office/outlook/12/
>electronicbusinesscards" ver="1.0" layout="left" bgcolor="ffffff"><img
>xml
>ns="" align="tleft" area="32" use="photo"/><fld xmlns="" prop="name"
>align
>="left" dir="ltr" style="b" color="000000" size="10"/><fld xmlns=""
>prop="
>org" align="left" dir="ltr" color="000000" size="8"/><fld xmlns=""
>prop="b
>lank" size="8"/><fld xmlns="" prop="telwork" align="left" dir="ltr"
>color=
>"000000" size="8"><label align="right"
>color="626262">Geschäftlich</label
>></fld><fld xmlns="" prop="email" align="left" dir="ltr" color="000000"
>si
>ze="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank"
>si
>ze="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank"
>si
>ze="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank"
>si
>ze="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank"
>si
>ze="8"/><fld xmlns="" prop="blank" size="8"/><fld xmlns="" prop="blank"
>si
> ze="8"/><fld xmlns="" prop="blank" size="8"/></card>
>X-MS-OL-DEFAULT-POSTAL-ADDRESS:0
>
>Is there a way for vdirsyncer to also ignore those fields? I know they
>are useless bloaty M$ XML blah, but it breaks functionality :/
>
>This is the normal output. If you need debug output, let me know!
>warning: Skipping
>'/.cloudy/remote.php/carddav/addressbooks/7e446f3d-c45d-4dd0-bd89-4f28356a3f1a/team/',
>etag property is missing.
>warning: Server sent unsolicited item:
>/.cloudy/remote.php/carddav/addressbooks/7e446f3d-c45d-4dd0-bd89-4f28356a3f1a/team/
>Unhandled exception occured for akt_contacts/team.
>Traceback (most recent call last):
>File "/usr/lib/python3.4/site-packages/vdirsyncer/cli/tasks.py", line
>65, in sync_collection
>    force_delete=force_delete
>File "/usr/lib/python3.4/site-packages/vdirsyncer/sync.py", line 163,
>in sync
>    b_info.prepare_idents(storage_a.read_only)
>File "/usr/lib/python3.4/site-packages/vdirsyncer/sync.py", line 111,
>in prepare_idents
>    if prefetch else ()):
>File "/usr/lib/python3.4/site-packages/vdirsyncer/storage/dav.py", line
>452, in get_multi
>    raise exceptions.NotFoundError(href)
>vdirsyncer.exceptions.NotFoundError:
>/.cloudy/remote.php/carddav/addressbooks/7e446f3d-c45d-4dd0-bd89-4f28356a3f1a/team/ebf32dc0-d6e1-4abc-abb2-14cb9f92f2c7@www.myserver.com.vcf
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/untitaker/vdirsyncer/issues/277

-- 
Sent from my phone. Please excuse my brevity.

**Comment by untitaker** [comment] 2015-10-27 17:55
@dvzrv Any update on this?

**Comment by dvzrv** [comment] 2015-10-30 14:54
Hey,
sorry, got busy doing other stuff.... and it's a problem I'd rather not be confronted with atm ;)

First of all, it's contacts, not calendars!
Someone duplicated all contacts around 10 times, so I have to try and get around that issue for a while. The whole setup seems to be messed up due to people's broken clients...

Will copy a broken card to one of my other address books and then try to repair.
Unfortunately since 0.7. there's this error:

```
critical: carddav storage doesn't take the parameters: password.fetch

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/vdirsyncer/cli/utils.py", line 350, in storage_instance_from_config
    return cls(**new_config)
  File "/usr/lib/python3.5/site-packages/vdirsyncer/storage/dav.py", line 366, in __init__
    super(DavStorage, self).__init__(**kwargs)
TypeError: __init__() got an unexpected keyword argument 'password.fetch'
critical: Failed to initialize akt_contacts_remote: __init__() got an unexpected keyword argument 'password.fetch'
```

**Comment by untitaker** [comment] 2015-10-30 14:59
>TypeError: __init__() got an unexpected keyword argument 'password.fetch'

I don't know how to reproduce this. `*.fetch` works fine for me. Could you paste your config for that?

**Comment by dvzrv** [comment] 2015-10-30 16:18
password.fetch works fine during sync... my head is scratched.
https://git.sleepmap.de/dotfiles.git/tree/.vdirsyncer/config

**Comment by untitaker** [comment] 2015-10-30 16:26
Sorry, didn't think about `repair`. That's a bug, I can reproduce. Fixed in master now I think, can you confirm?

**Comment by untitaker** [comment] 2015-12-17 03:50
Closing this due to lack of activity.

**Closed by untitaker** 2015-12-17 03:50 UTC
Labels: 3rd party, storage: DAV

**Comment by strk** [comment] 2020-07-14 07:19
@dvzrv is outlook the same as office365 ? (sorry for my ignorance about proprietary systems) - if it is, can you share instructions about setting up caldav sync with it ?
