### ISSUE TITLE
"SyncError: Etag changed during sync" with ownCloud birthday calendar

### ISSUE THREAD

**Issue by sixtyfive** [untitaker/vdirsyncer#262] opened 2015-09-03 00:04 UTC
So this is my last remaining issue for today. Couldn't figure it out by way of logs or Google. The main calendar (with actual events in it) syncs just fine. Then this happens when the birthday calendar is synced:

```
$ vdirsyncer -v INFO sync calendar
Syncing calendar/defaultcalendar
Syncing calendar/contact_birthdays
Unhandled exception occured for calendar/contact_birthdays.
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/vdirsyncer/cli/tasks.py", line 58, in sync_collection
    force_delete=force_delete
  File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 163, in sync
    b_info.prepare_idents(storage_a.read_only)
  File "build/bdist.linux-x86_64/egg/vdirsyncer/sync.py", line 116, in prepare_idents
    raise SyncError('Etag changed during sync.')
SyncError: Etag changed during sync.
```

The folder is empty afterwards, but `-v DEBUG` reveals that all birthdays are actually downloaded from the server and some (?) are considered "already normalized" before the exception occurs.

**Comment by untitaker** [comment] 2015-09-03 00:33
I suspect that this is another bug in ownCloud. They have introduced so many bugs in their newest release that I had to turn off the testsuite for it.

**Comment by sixtyfive** [comment] 2015-09-03 13:34
Ouch. Well, they also did things like made the "Contacts" app a non-approved "3rd-party" app. Waiting for someone to fork it and save it from a corporate future of irrelevancy. Anyways, how do you debug it?

**Comment by untitaker** [comment] 2015-09-03 13:46
You can use `vdirsyncer -vdebug ...` to see the HTTP requests made to the server, there you will probably see that ownCloud responds with two different etags when requesting the same item twice. You can probably use this to see whether ownCloud returns a completely different etag, or whether there's just some inconsistency in the formatting (surrounded with `"`-quotes vs. not). I've just pushed a commit to master that just shows the two etags in the error message though, so you can install vdirsyncer from git and also see the difference.

Note that this exception can also occur if another client modifies the item while vdirsyncer is syncing. This is the primary reason why vdirsyncer compares etags, not to detect buggy servers. However, in that case the above error would not be constantly reproducible, and a second `sync` will probably succeed.

The ownCloud error log probably doesn't help with this, although if there are errors occuring, it's definetly noteworthy.

**Comment by sixtyfive** [comment] 2015-09-03 20:55
Okay, installed the current version from git. Then I ran `vdirsyncer sync calendar` a couple of times and noticed a pattern: two syncs will complete without error (the always-same items are updated) and then the third sync will show the "Etag changed" error. The two Etags are *not* always the same, but they are always different from one another, i.e. `'"ecc5499ec1861edb08a69c070e343976"'` and `u'"10a411e54d5d47159e15feef9070d4d5"'`. They *are*, however, different from the items which are claimed to have been updated successfully, which always look like `1806fbb0-6172-40ef-ab66-fa4f564591cb` or `d18ac62f-aea9-46d7-8858-862fc9f6926c@mydomain` instead.

**Comment by untitaker** [comment] 2015-09-03 21:39
Could you try disabling any other clients that you may have pointed to either OC contacts or calendars?

**Comment by sixtyfive** [comment] 2015-09-04 08:10
Hmm, the only thing that accessed OC was the web client which was open in a browser tab. If anything, today the error occurs more randomly. Definitely not the 2-times okay, 1-time error behaviour I described yesterday. Not sure what to make of it...

**Comment by sixtyfive** [comment] 2015-09-04 08:11
(Did you only mean OC clients accessing *my* account or *any* account btw?)

**Comment by untitaker** [comment] 2015-09-04 12:19
>(Did you only mean OC clients accessing my account or any account btw?)

Only yours.

I'd recommend disabling all clients (including closing the webinterface). Also the contact clients. There might be a contacts app that is constantly hammering the server, updating contacts.

**Comment by sixtyfive** [comment] 2015-09-04 22:06
Sorry, I should have been clearer that, after your comment about this perhaps being caused by concurrent access, I shut down *all* of my other clients, *including* the web client. The second-to-last comment was meant to say that even so, the error still occurs every couple of calendar syncs (contact syncs never seem to fail at all).

**Comment by untitaker** [comment] 2015-09-08 00:25
I tried to create a simple contact locally but couldn't reproduce this. Could you figure out which contact belongs to that everchanging item?

**Comment by sixtyfive** [comment] 2015-09-16 10:05
Sorry, no. Actually, these items don't seem to belong to any contacts at all. As I said, their tags are never twice the same and no matter how many of them I download, they never contain any useful information. I also checked to see whether I have any empty accounts (= no useful information), but there are only valid contacts in the database (or at least: only valid ones are shown).

**Comment by untitaker** [comment] 2015-09-19 22:23
@sixtyfive FWIW I've changed that check to a warning in master because it wasn't strictly necessary in the first place. Yes, the server behaves badly, but there may be instances of this exception where the server is not at fault, in either case sync can work around it.

**Comment by untitaker** [comment] 2015-09-19 22:24
Closing this since

* It's not an issue with vdirsyncer
* I can't really reproduce this, so the info we got isn't fit for a ownCloud bugreport.

**Closed by untitaker** 2015-09-19 22:24 UTC
Labels: 3rd party, bug

**Comment by sixtyfive** [comment] 2015-09-19 22:29
Thank you for changing it to a warning and sorry I wasn't able to provide more (useful) information. FWIW, it being a warning is just the right thing IMHO. Have a nice weekend! :)

**Comment by untitaker** [comment] 2015-09-19 22:31
Thanks, you too!
