### ISSUE TITLE
vdirsyncer complains about missing collections

### ISSUE THREAD

**Issue by MacGyverNL** [untitaker/vdirsyncer#276] opened 2015-09-27 20:03 UTC
This configuration was working before, I updated both vdirsyncer and radicale recently. vdirsyncer complains about not finding collections for remotes. Non-debug output of discover: 
```
Discovering collections for pair pol_calendars_readwrite
Discovering collections for pair pol_calendars_external
Discovering collections for pair pol_contacts
Saved for pol_contacts: collections = null
error: No collection university.ics found for storage pol_calendars_readwrite_remote.
Should vdirsyncer attempt to create it? [y/N]: 
error: No collection mozilla-dutchholidays.ics found for storage pol_calendars_external_local.
Should vdirsyncer attempt to create it? [y/N]: 
critical: Unable to find or create collection "university.ics" for storage "pol_calendars_readwrite_remote". Please create the collection yourself
critical: Unable to find or create collection "mozilla-dutchholidays.ics" for storage "pol_calendars_external_local". Please create the collection yourself
```

There's more calendars in those collections, and every time it asks me the question about a randomly selected calendar in a collection. If I do tell it to create the collection, I get
```
Discovering collections for pair pol_contacts
Discovering collections for pair pol_calendars_readwrite
Discovering collections for pair pol_calendars_external
Saved for pol_contacts: collections = null
error: No collection university.ics found for storage pol_calendars_readwrite_remote.
Should vdirsyncer attempt to create it? [y/N]: y
error: No collection persoonlijkrooster.ru.nl.ics found for storage pol_calendars_external_remote.
Should vdirsyncer attempt to create it? [y/N]: y
error: 500 Server Error: Internal Server Error
critical: Unable to find or create collection "university.ics" for storage "pol_calendars_readwrite_remote". Please create the collection yourself
error: 500 Server Error: Internal Server Error
critical: Unable to find or create collection "persoonlijkrooster.ics" for storage "pol_calendars_external_remote". Please create the collection yourself
```

My configuration file, censored somewhat, is:
```
[general]
status_path = ~/.config/vdirsyncer/status/

[pair pol_contacts]
a = pol_contacts_local
b = pol_contacts_remote

[storage pol_contacts_local]
type = filesystem
path = ~/.contacts/
fileext = .vcf

[storage pol_contacts_remote]
type = carddav
url = https://url.myserver.example:5232/ZZZZZZ/contacts/contacts.vcf/
auth = basic
username = ZZZZZZ
password = XXXXXX
verify = ~/.config/vdirsyncer/url.myserver.example.crt

# CALDAV
[pair pol_calendars_readwrite]
a = pol_calendars_readwrite_local
b = pol_calendars_readwrite_remote
collections = ["personal.ics","university.ics"]
conflict_resolution = null

[storage pol_calendars_readwrite_local]
type = filesystem
path = ~/.calendars/ZZZZZZ/
fileext = .ics

[storage pol_calendars_readwrite_remote]
type = caldav
url = https://url.myserver.example:5232/ZZZZZZ/calendars/
auth = basic
username = ZZZZZZ
password = XXXXXX
verify = ~/.config/vdirsyncer/url.myserver.example.crt
read_only = false

[pair pol_calendars_external]
a = pol_calendars_external_local
b = pol_calendars_external_remote
collections = ["afvalkalender.ics","groupware.ics","googlekn.ics","mozilla-dutchholidays.ics","persoonlijkrooster.ics"]
conflict_resolution = "b wins"

[storage pol_calendars_external_local]
type = filesystem
path = ~/.calendars/external/
fileext = .ics

[storage pol_calendars_external_remote]
type = caldav
url = https://url.myserver.example:5232/readonly/external/calendars/
auth = basic
username = ZZZZZZ
password = XXXXXX
verify = ~/.config/vdirsyncer/url.myserver.example.crt
read_only = true
```

**Comment by MacGyverNL** [comment] 2015-09-27 20:36
Debug output of vdirsyncer: https://ptpb.pw/LFjy
Debug output of radicale for the same conversation: https://ptpb.pw/z-S_

**Comment by untitaker** [comment] 2015-09-28 15:46
We talked about this in IRC. The root cause of this is that @MacGyverNL puts his collections into subfolders (`calendars`), but Radicale doesn't know how to deal with that. A PROPFIND on the `calendar-home-set` URL only gives us `calendars`, and vdirsyncer assumes that to be a proper calendar (since Radicale reports it to be a folder).

Radicale is at fault here. Either it should disallow custom nesting of calendars, or do proper responses when requesting all `calendar-home-set`s of a principal.

**Comment by untitaker** [comment] 2015-09-30 15:49
@MacGyverNL any update on this?

**Comment by MacGyverNL** [comment] 2015-10-01 10:51
As it stands I worked around it by creating a single pair for each calendar and passing the absolute URL for each one. I've opened an issue at Radicale, Kozea/Radicale#321.

Updates on this from me will be sparse in the coming weeks, though.

**Comment by untitaker** [comment] 2015-10-27 17:55
I guess I can close this one, it's just a bug in Radicale.

**Closed by untitaker** 2015-10-27 17:55 UTC
Labels: 3rd party, DAV
